#!/usr/bin/env python
# -*- coding: utf-8 -*-
# author: Gaterny

import csv

# 写入csv文件，writer方法、writerow方法
with open('data.csv', 'w', encoding='utf-8') as csvfile:
    writer = csv.writer(csvfile, delimiter=' ')          # 初始化写入对象,delimiter指定每列之间以空格分隔
    writer.writerow(['city', 'name', 'age', 'class'])    # writerow()传入每行的数据
    writer.writerow(['xian', 'tom', '13', '1'])
    writer.writerow(['hefei', 'bob', '15', '1'])
    writer.writerow(['beijing', 'rita', '14', '1'])
    # 也可以一次写入多行
    # writer.writerows([['city', 'name', 'age', 'class'], ['xian', 'tom', '13', '1'],[ 'hefei', 'bob', '15', '1'], ['beijing', 'rita', '14', '1']])

# 写入字典数据
with open('dict.csv', 'w') as csvfile:
    fieldnames = ['city', 'name', 'age']    # 定义字段
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)   # 初始化字典写入对象
    writer.writeheader()   # 写入头信息
    writer.writerow({'city':'xian', 'name':'tom', 'age':'13'})  # 写入每行数据

# 从文件中读取csv文件，reader方法接收可迭代对象作为参数
with open ('data.csv', newline='') as f:
    readers = csv.reader(f)
    for row in readers:
        print(row)
# ['city name age class']
# ['xian tom 13 1']
# ['hefei bob 15 1']
# ['beijing rita 14 1']


# 对csv文件增加列
import csv

with open('./yangben.csv', encoding='utf8') as f:
    rows = csv.reader(f)
    with open('transf.csv', 'w',encoding='utf8', newline='') as f:   # newline='' 防止在windows下自动生成空行
        writer = csv.writer(f)
        for row in rows:
            print(row)
            row.insert(0,1)  # or row.append()在末尾增加列
            writer.writerow(row)
