#!/usr/bin/env python
# -*- coding: utf-8 -*-

# json字符串的数据用双引号表示
import json

# loads()方法将json文件转换成可操作的数据结构，比如字典和列表
data = json.loads(a_str)
print(data)

# dumps()方法将json对象转换成字符串

with open ('test.json', 'w') as f:
    f.write(json.dumps(test, indent=2，ensure_ascii=False))  # indent表示缩进字符个数,ensure_ascii=False规定编码，可以输出中文
